name: My first workflow
on: [push]

jobs: Jobs
  run_command: Job
    runs-on: ubuntu-latest
    steps: 1
      - name run command echo
        run: echo "Hello world"
       - name run multiple commands
        run: echo "Hello world"
         echo "Hello world"
         echo "This is Github"
